version: "3"
services:
  mongo:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"

    volumes:
      - dbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nodebb
      - MONGODB_ROOT_PASSWORD=root

volumes:
  dbdata:
