version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER=root
      - MONGODB_PASS=root
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
volumes:
  dbdata:
  mongodata:
